licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

py_library(
    name = "tensorflow_addons",
    data = [
        "__init__.py",
        "version.py",
    ],
)
