licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

py_library(
    name = "tensorflow_addons",
    data = [
        "__init__.py",
        "version.py",
    ],
    deps = [
        "//tensorflow_addons/activations",
        "//tensorflow_addons/callbacks",
        "//tensorflow_addons/image",
        "//tensorflow_addons/layers",
        "//tensorflow_addons/losses",
        "//tensorflow_addons/metrics",
        "//tensorflow_addons/optimizers",
        "//tensorflow_addons/rnn",
        "//tensorflow_addons/seq2seq",
        "//tensorflow_addons/text",
    ],
)
