py_runtime(
	name = "python2.7.6",
	files = [],
	interpreter_path = "/usr/bin/python",
	visibility = ["//visibility:public"]
)

py_runtime(
	name = "python3.4.3",
	files = [],
	interpreter_path = "/usr/bin/python3",
	visibility = ["//visibility:public"]
)
