licenses(["notice"])  # Apache 2.0

package(default_visibility = ["//visibility:public"])

py_library(
    name = "utils_py",
    srcs = ([
        "__init__.py",
        "keras_utils.py",
        "test_utils.py",
        "resource_loader.py",
    ]),
    srcs_version = "PY2AND3",
)
