name: GitHub CI

on:
  push:
    branches:
      - master
      - r*
  pull_request:
    branches:
      - master
      - r*


jobs:
  valid-codeowners:
    name: Check that the CODEOWNERS is valid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Check that the CODEOWNERS is valid
        run: python .github/workflows/notify_codeowners/main.py .github/CODEOWNERS
