name: nightly-tests

on:
  schedule:
    # Shortly after tf-nightly is released
    - cron:  '0 11 * * *'

env:
  BAZEL_VERSION: 1.1.0

jobs:
  macos-nightly:
    name: Test nightly on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: ['3.7']
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Nightly test macOS py${{ matrix.python-version }}
        run: |
          set -x -e
          python -m pip install wheel setuptools
          python --version
          wget --quiet -nc https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh
          chmod +x bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh
          ./bazel-${BAZEL_VERSION}-installer-darwin-x86_64.sh --user
          bash -x -e tools/ci_testing/addons_cpu.sh
