name: ubuntu-cpu-nightly

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  ubuntu-cpu-nightly:
    name: Test nightly on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Nightly test Ubuntu
        run: |
          set -x -e
          bash tools/run_docker.sh -d cpu -c 'make unit-test'
  manylinux-nightly-release:
    name: Build and release nightly for manylinux2010
    env:
      PYPI_PW: ${{ secrets.pypi_password }}
    needs: [ubuntu-cpu-nightly]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Nightly build and release for Linux
        run: |
          docker run -e TF_NEED_CUDA=1 -v ${PWD}:/addons -w /addons gcr.io/tensorflow-testing/nosla-cuda10.1-cudnn7-ubuntu16.04-manylinux2010 tools/ci_build/builds/release_linux.sh
          python -m pip install -U twine
          twine upload -u __token__ -p $PYPI_PW wheelhouse/*.whl
