
name: ubuntu-cpu-nightly

on:
  schedule:
    - cron:  '0 11 * * *'

env:
  BAZEL_VERSION: 1.1.0

jobs:
  ubuntu-cpu-nightly:
    name: Test nightly on Ubuntu
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: Nightly test Ubuntu
        run: |
          set -x -e
          bash tools/run_docker.sh -d cpu -c 'make unit-test'
